export const TRIPS = 'TRIPS';
export const CREATE_TRIP = 'CREATE_TRIP';
export const TRIP_DETAIL = 'TRIP_DETAIL';
export const TRAVELER_DETAIL = 'TRAVELER_DETAIL';
export const SEARCH_TRAVELER_PACKAGE = 'SEARCH_TRAVELER_PACKAGE';
