export const REVIEWS = "REVIEWS";
export const CREATE_REVIEW = "CREATE_REVIEW";
export const TRAVELER_REVIEWS = "TRAVELER_REVIEWS";
export const UPDATE_REVIEW = "UPDATE_REVIEW";
export const DELETE_REVIEW = "DELETE_REVIEW";
