export const PACKAGES = 'PACKAGES';
export const SEND_PACKAGE = 'SEND_PACKAGE';
export const PACKAGE_CATEGORIES = 'PACKAGE_CATEGORIES';
export const SENDER_PACKAGES = 'SENDER_PACKAGES';
export const SEARCH_SENDER_PACKAGE = 'SEARCH_SENDER_PACKAGE';
